version: '3.8'

services:
  clientes-db:
    image: postgres:15
    container_name: clientes-db
    environment:
      POSTGRES_DB: clientes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - clientes_data:/var/lib/postgresql/data

  clientes-service:
    build: .
    container_name: clientes-service
    depends_on:
      - clientes-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://clientes-db:5432/clientes_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  clientes_data:
